import { numericTypedArrayConstructors } from "../../interp/typed-array-constructors.js";

export const KNOWN_RUNTIME_GLOBALS = [
  "AggregateError",
  "Array",
  "ArrayBuffer",
  "DataView",
  "Boolean",
  "BigInt",
  "Date",
  "DisposableStack",
  "decodeURI",
  "decodeURIComponent",
  "encodeURI",
  "encodeURIComponent",
  "Error",
  "EvalError",
  "Infinity",
  "isFinite",
  "isNaN",
  "Iterator",
  "JSON",
  "Map",
  ...Object.keys(numericTypedArrayConstructors),
  "Math",
  "NaN",
  "Number",
  "Object",
  "parseFloat",
  "parseInt",
  "Promise",
  "RangeError",
  "ReferenceError",
  "Reflect",
  "RegExp",
  "Set",
  "String",
  "SuppressedError",
  "Symbol",
  "structuredClone",
  "SyntaxError",
  "TypeError",
  "URIError",
  "console"
] as const;
